### ISSUE TITLE
Write journal article about NWBib spatial & Wikidata

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-blog#73]
By now, we have set this up nearly completely (with the update process not being fully implemented, see https://github.com/hbz/nwbib/issues/547). At #swib20 there was some interest in the approach (search for `#NWBib` in the Town Square to the the thread) and I think we should publish a blog post about the implementation process and the resulting setup.

**Comment by acka47** [comment]
The draft post is now pending review by @pkiraly for Code4Lib. As time was short, I just now sent a version to hbz marketing for information. If some typo or phrasing fixes come in from marketing, I will incorporate them into the draft.

**Comment by acka47** [comment]
Closing, will be published 2021-06-10

**Comment by pkiraly** [comment]
One note: before publication the Code4Lib Journal's editoral team will vote about the publication.
