### ISSUE TITLE
Unable to install locally

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-blog#92]
Following the README I got:
>$ jekyll serve --drafts --watch
/var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find concurrent-ruby-1.2.2 in any of the sources (Bundler::GemNotFound)

Tried some of the things internet proposes, but no luck.

**Comment by acka47** [comment]
I also had error reports (other than yours) that could be solved with using `bundle exec jekyll serve --drafts --watch`.

**Comment by dr0i** [comment]
@acka47 perfect - this does the trick :+1:
